<?php

/*
 * This file is part of Octower.
 *
 * (c) William Pottier <developer@william-pottier.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Octower\Deploy\SharedGenerator;

use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Yaml\Parser;
use Symfony\Component\Yaml\Yaml;

class DistYamlFileGenerator implements GeneratorInterface
{
    public function __construct()
    {

    }

    public function generate(Filesystem $filesystem, $projectRoot, $sharedPath, $path)
    {
        $distFile = $projectRoot . DIRECTORY_SEPARATOR . $path . '.dist';
        $yamlParser = new Parser();

        $distValues = $yamlParser->parse(file_get_contents($distFile));

        file_put_contents($path, "# This file is auto-generated by octower\n" . Yaml::dump($distValues, 99));
    }

    public function update(Filesystem $filesystem, $projectRoot, $sharedPath, $path)
    {
        $distFile = $projectRoot . DIRECTORY_SEPARATOR . $path . '.dist';
        $yamlParser = new Parser();

        $distValues = $yamlParser->parse(file_get_contents($distFile));
        $existingValues = $yamlParser->parse(file_get_contents($path));

        $actualValues = array_merge($distValues, $existingValues);

        file_put_contents($path, "# This file is auto-generated by octower\n" . Yaml::dump($actualValues, 99));
    }
}